import { IconButton } from "@mui/material";
import CustomTooltip from "../../CustomTooltip";
import EditIcon from "@mui/icons-material/Edit";
import CustomModal from "../../Modal";
import { useLanguageContext } from "../../../../context/LanguageContext";
import { useState } from "react";
import CreateForm from "../../../AutoGeneratedForms/CreateForm";
import { Query } from "../../../../API/callApi";
type EditActionProps = {
  selectedRow: any;
  columns: any;
  actionUrl: string;
  setAnchorEl: any;
  configurations: any;
  setFinalRows: any;
  getQuery: Query;
};

export const EditAction = ({
  selectedRow,
  columns,
  actionUrl,
  setAnchorEl,
  configurations,
  setFinalRows,
  getQuery,
}: EditActionProps) => {
  const { t } = useLanguageContext();

  const [open, setOpen] = useState<string | null>(null);
  return (
    <>
      <CustomTooltip title={t("Edit")} placement="bottom">
        <IconButton
          onClick={() => {
            setOpen("open");
            setAnchorEl("closeOnlyAnchor");
          }}
        >
          <EditIcon fontSize="small" />
        </IconButton>
      </CustomTooltip>

      <CustomModal
        open={!!open}
        onClose={() => setOpen(null)}
        title={t("Edit")}
        width={"lg"}
      >
        {columns.length !== 0 && (
          <CreateForm
            columns={columns}
            actionUrl={actionUrl}
            setModalTitle={setOpen}
            selectedRow={selectedRow}
            configurations={configurations}
            setFinalRows={setFinalRows}
            getQuery={getQuery}
          />
        )}
      </CustomModal>
    </>
  );
};
