import { useState } from "react";
import { useLanguageContext } from "../../../context/LanguageContext";
import { IconButton, Stack } from "@mui/material";
import AddOutlinedIcon from "@mui/icons-material/AddOutlined";
import CustomModal from "../../MaterialUI/Modal";
import CustomTooltip from "../../MaterialUI/CustomTooltip";
import CreateForm from "../../AutoGeneratedForms/CreateForm";

interface InvoiceRightMenuProps {
  setRefreshTable: React.Dispatch<React.SetStateAction<boolean>>;
  columns: any;
}

const ClientsRightMenu: React.FC<InvoiceRightMenuProps> = ({
  // setRefreshTable,
  columns,
}) => {
  // console.log(columns);
  const { t } = useLanguageContext();

  const [modalTitle, setModalTitle] = useState<any | null>(null);
  return (
    <>
      <Stack alignItems="center">
        <Stack alignItems="center">
          <CustomTooltip title={t("Add")}>
            <IconButton
              aria-label="Add new Client"
              onClick={() => setModalTitle("Add new Client")}
            >
              <AddOutlinedIcon />
            </IconButton>
          </CustomTooltip>
        </Stack>
      </Stack>

      <CustomModal
        open={!!modalTitle}
        onClose={() => setModalTitle(null)}
        title="Add New Client"
        width={"lg"}
        style="create"
        titleIcon="create"
      >
        {columns.length !== 0 && (
          <CreateForm
            columns={columns}
            actionUrl="gym/members"
            setModalTitle={setModalTitle}
          />
        )}
      </CustomModal>
    </>
  );
};

export default ClientsRightMenu;
