import { IconButton } from "@mui/material";
import CustomTooltip from "../CustomTooltip";
import InfoIcon from "@mui/icons-material/Info";
import CustomModal from "../Modal";
import { useLanguageContext } from "../../../context/LanguageContext";
import { useState } from "react";
import CreateForm from "../../AutoGeneratedForms/CreateForm";
type DetailsActionProps = {
  selectedRow: any;
  columns: any;
  actionUrl: string;
};

export const DetailsAction = ({
  selectedRow,
  columns,
  actionUrl,
}: DetailsActionProps) => {
  const { t } = useLanguageContext();

  const [open, setOpen] = useState<boolean | null>(false);
  return (
    <>
      <CustomTooltip title="Details" placement="bottom">
        <IconButton
          onClick={() => {
            setOpen(true);
          }}
        >
          <InfoIcon fontSize="small" />
        </IconButton>
      </CustomTooltip>

      <CustomModal
        open={!!open}
        onClose={() => setOpen(false)}
        title={t("Details")}
        width={"md"}
        style="info"
        titleIcon="info"
      >
        {columns.length !== 0 && (
          <CreateForm
            disabled={true}
            columns={columns}
            actionUrl={actionUrl}
            setModalTitle={setOpen}
            selectedRow={selectedRow}
          />
        )}
      </CustomModal>
    </>
  );
};
