import { IconButton } from "@mui/material";
import CustomTooltip from "../CustomTooltip";
import InfoIcon from "@mui/icons-material/Info";
import CustomModal from "../Modal";
import { useLanguageContext } from "../../../context/LanguageContext";
import CreateForm from "../../AutoGeneratedForms/CreateForm";
type DetailsActionProps = {
  selectedRow: any;
  columns: any;
  actionUrl: string;
  open: boolean;
  setOpen: any;
  setAnchorEl: any;
};

export const DetailsAction = ({
  selectedRow,
  columns,
  actionUrl,
  open,
  setOpen,
  setAnchorEl,
}: DetailsActionProps) => {
  const { t } = useLanguageContext();

  return (
    <>
      <CustomTooltip title="Details" placement="bottom">
        <IconButton
          onClick={() => {
            setOpen(true);
            setAnchorEl("closeOnlyAnchor");
          }}
        >
          <InfoIcon fontSize="small" />
        </IconButton>
      </CustomTooltip>

      <CustomModal
        open={!!open}
        onClose={() => {
          setOpen(false);
          setAnchorEl(null);
        }}
        title={t("Details")}
        width={"lg"}
        style="info"
        titleIcon="info"
      >
        {columns.length !== 0 && (
          <CreateForm
            disabled={true}
            columns={columns}
            actionUrl={actionUrl}
            setModalTitle={setOpen}
            selectedRow={selectedRow}
            setAnchorEl={setAnchorEl}
          />
        )}
      </CustomModal>
    </>
  );
};
