import { IconButton } from "@mui/material";
import CustomTooltip from "../CustomTooltip";
import EditIcon from "@mui/icons-material/Edit";
import CustomModal from "../Modal";
import { useLanguageContext } from "../../../context/LanguageContext";
import { useState } from "react";
import CreateForm from "../../AutoGeneratedForms/CreateForm";
type EditActionProps = {
  selectedRow: any;
  columns: any;
  actionUrl: string;
};

export const EditAction = ({
  selectedRow,
  columns,
  actionUrl,
}: EditActionProps) => {
  const { t } = useLanguageContext();

  const [open, setOpen] = useState<boolean | null>(false);
  return (
    <>
      <CustomTooltip title="Edit" placement="bottom">
        <IconButton
          onClick={() => {
            setOpen(true);
          }}
        >
          <EditIcon fontSize="small" />
        </IconButton>
      </CustomTooltip>

      <CustomModal
        open={!!open}
        onClose={() => setOpen(false)}
        title={t("Edit")}
        width={"md"}
        style="edit"
        titleIcon="edit"
      >
        {columns.length !== 0 && (
          <CreateForm
            columns={columns}
            actionUrl={actionUrl}
            setModalTitle={setOpen}
            selectedRow={selectedRow}
          />
        )}
      </CustomModal>
    </>
  );
};
