import { useState } from "react";
import { useLanguageContext } from "../../../context/LanguageContext";
import { IconButton, Stack } from "@mui/material";
import AddOutlinedIcon from "@mui/icons-material/AddOutlined";
import CustomModal from "../Modal";
import CustomTooltip from "../CustomTooltip";
import CreateForm from "../../AutoGeneratedForms/CreateForm";
import { Column, Configuration } from "../../../Global/Types/commonTypes";

interface RightMenuProps {
  setRefreshTable: React.Dispatch<React.SetStateAction<boolean>>;
  columns: Column[];
  addNew?: boolean;
  configurations?: Configuration;
  title: string;
  createUrl: string;
}

const RightMenu: React.FC<RightMenuProps> = ({
  setRefreshTable,
  columns,
  addNew,
  configurations,
  title,
  createUrl,
}) => {
  const { t } = useLanguageContext();

  const [modalTitle, setModalTitle] = useState<string | null>(null);
  return (
    <>
      <Stack alignItems="center">
        <Stack alignItems="center">
          <CustomTooltip title={t("Add")}>
            <IconButton
              aria-label={`${t("Add new")} ${title}`}
              onClick={() => setModalTitle("Add new")}
            >
              <AddOutlinedIcon />
            </IconButton>
          </CustomTooltip>
        </Stack>
      </Stack>
      {modalTitle && (
        <CustomModal
          open={!!modalTitle}
          onClose={() => setModalTitle(null)}
          title={`${t(modalTitle)} ${title}`}
          width={"lg"}
        >
          {modalTitle === "Add new" && addNew && columns.length !== 0 && (
            <CreateForm
              setRefreshTable={setRefreshTable}
              columns={columns}
              configurations={configurations}
              actionUrl={createUrl}
              setModalTitle={setModalTitle}
            />
          )}
        </CustomModal>
      )}
    </>
  );
};

export default RightMenu;
