import { useState } from "react";
import { useLanguageContext } from "../../../context/LanguageContext";
import { IconButton, Stack } from "@mui/material";
import AddOutlinedIcon from "@mui/icons-material/AddOutlined";
import CustomModal from "../Modal";
import CustomTooltip from "../CustomTooltip";
import CreateForm from "../../AutoGeneratedForms/CreateForm";
import { Column, Configuration } from "../../../Global/Types/commonTypes";

interface RightMenuProps {
  setRefreshTable: React.Dispatch<React.SetStateAction<boolean>>;
  columns: Column[];
  addNew?: boolean;
  configurations?: Configuration;
}

const RightMenu: React.FC<RightMenuProps> = ({
  setRefreshTable,
  columns,
  addNew,
  configurations,
}) => {
  const { t } = useLanguageContext();

  const [modalTitle, setModalTitle] = useState<string | null>(null);
  return (
    <>
      <Stack alignItems="center">
        <Stack alignItems="center">
          <CustomTooltip title={t("Add")}>
            <IconButton
              aria-label="Add new Client"
              onClick={() => setModalTitle("Add new Client")}
            >
              <AddOutlinedIcon />
            </IconButton>
          </CustomTooltip>
        </Stack>
      </Stack>

      <CustomModal
        open={!!modalTitle}
        onClose={() => setModalTitle(null)}
        title="Add New Client"
        width={"lg"}
      >
        {addNew && columns.length !== 0 && (
          <CreateForm
            setRefreshTable={setRefreshTable}
            columns={columns}
            configurations={configurations}
            actionUrl="staff-members/staff"
            setModalTitle={setModalTitle}
          />
        )}
      </CustomModal>
    </>
  );
};

export default RightMenu;
