import React, { useEffect, useState } from "react";
import CreateForm from "../../AutoGeneratedForms/CreateForm";
import {
  Box,
  Divider,
  Grid,
  MenuItem,
  Paper,
  Step,
  StepLabel,
  Stepper,
  ToggleButton,
  ToggleButtonGroup,
  Typography,
} from "@mui/material";
import TextField from "../../MaterialUI/FormFields/TextField";
import { useLanguageContext } from "../../../context/LanguageContext";
import callApi, { Query } from "../../../API/callApi";
import { useAuthedContext } from "../../../context/AuthContext";
import Button from "../../MaterialUI/Button";
import {
  getQueryOptions,
  postMember,
  postSubscription,
} from "../../../pages/Access Control/API/getQueries";
import Alert from "../../MaterialUI/Alert";
import DatePickerComponent from "../../MaterialUI/FormFields/DatePicker";
import CustomModal from "../../MaterialUI/Modal";

interface ClientsCreateFormProps {
  setRefreshTable: any;
  columns: any;
  setModalTitle: any;
}

const steps = ["Person Info", "Plan", "Payment"];

const ClientsCreateForm: React.FC<ClientsCreateFormProps> = ({
  setRefreshTable,
  setModalTitle,
  columns,
}) => {
  const { setAuthedUser } = useAuthedContext();
  const { t } = useLanguageContext();
  const [openConfirm, setOpenConfirm] = useState<boolean>(false);
  const [activeStep, setActiveStep] = useState<number>(0);
  const [options, setOptions] = useState<any>([]);
  const [formData, setFormData] = useState<any>({});
  const [errors, setErrors] = useState<{ [key: string]: string }>({});
  const [subscriptionData, setSubscriptionData] = useState<any>({});
  const [id, setId] = useState<any>({});
  const [paymentMethod, setPaymentMethod] = useState<"card" | "cash" | null>(
    null
  );

  const handlePaymentMethodChange = (
    event: React.MouseEvent<HTMLElement>,
    newMethod: "card" | "cash" | null
  ) => {
    if (newMethod !== null) {
      setPaymentMethod(newMethod);
    }
  };

  const handleNext = async () => {
    if (activeStep === 0) {
      const response = await callApi<any>({
        query: postMember(formData),
        auth: { setAuthedUser },
      });
      response.success === false && setErrors(response.validationErrors);
      response.success === true && setId(response.data.id);
      response.success === true &&
        setActiveStep((prevActiveStep) =>
          Math.min(prevActiveStep + 1, steps.length - 1)
        );
    } else if (activeStep === 1) {
      setActiveStep((prevActiveStep) =>
        Math.min(prevActiveStep + 1, steps.length - 1)
      );
    } else if (activeStep === 2) {
      setOpenConfirm(true);
    }
  };

  const handleBack = () => {
    setActiveStep((prevActiveStep) => Math.max(prevActiveStep - 1, 0));
  };

  const handleChange = (field: string, value: string): void => {
    setFormData((prev: any) => ({
      ...prev,
      [field]: value,
    }));
  };
  const handleChangSubscription = (field: string, value: string): void => {
    setSubscriptionData((prev: any) => ({
      ...prev,
      [field]: value,
    }));
  };

  useEffect(() => {
    const fetchAllOptions = async () => {
      if (!columns) return;

      const optionsMap: Record<string, any[]> = {};

      for (const col of columns) {
        const isDropdown = col.dropDownConfig?.url;
        const isEnum = col.enumConfig?.url;

        if (isDropdown || isEnum) {
          const rawUrl = col.dropDownConfig?.url || col.enumConfig?.url;
          const url = rawUrl.startsWith("/v1/") ? rawUrl.slice(4) : rawUrl;

          try {
            const options = await callApi<any>({
              query: getQueryOptions(url),
              auth: { setAuthedUser },
            });
            options.success && (optionsMap[col.field] = options.data);
            !options.success &&
              console.error("Error fetching options for: ", col.field);
          } catch (error) {
            console.error("Error fetching options for", col.field, error);
          }
        }
      }

      setOptions(optionsMap);
    };

    fetchAllOptions();
  }, [columns]);

  const getStepContent = (step: number) => {
    switch (step) {
      case 0:
        return (
          //   <CreateForm
          //     setRefreshTable={setRefreshTable}
          //     columns={columns}
          //     configurations={configurations}
          //     setActiveStep={setActiveStep}
          //     actionUrl="gym-members/members"
          //   />
          <Grid container spacing={2} p={2}>
            <Grid size={6}>
              <TextField
                label={t("First Name")}
                value={formData.firstName}
                onChange={(e) => handleChange("firstName", e.target.value)}
                error={!!errors["firstName"]}
                helperText={errors["firstName"]}
                fullWidth
              />
            </Grid>
            <Grid size={6}>
              <TextField
                label={t("Last Name")}
                value={formData.lastName}
                onChange={(e) => handleChange("lastName", e.target.value)}
                error={!!errors["lastName"]}
                helperText={errors["lastName"]}
                fullWidth
              />
            </Grid>
            <Grid size={6}>
              <TextField
                label={t("Email")}
                value={formData.email}
                onChange={(e) => handleChange("email", e.target.value)}
                error={!!errors["email"]}
                helperText={errors["email"]}
                fullWidth
              />
            </Grid>
            <Grid size={6}>
              <TextField
                label={t("Phone")}
                value={formData.phone}
                onChange={(e) => handleChange("phone", e.target.value)}
                error={!!errors["phone"]}
                helperText={errors["phone"]}
                fullWidth
              />
            </Grid>
            <Grid size={6}>
              <DatePickerComponent
                sx={{ width: "100%", margin: 0 }}
                label={t("Birth Date")}
                value={formData.birthDate}
                onChange={(newValue: any) =>
                  handleChange("birthDate", newValue)
                }
                error={!!errors["birthDate"]}
                helperText={errors["birthDate"]}
              />
            </Grid>
            <Grid size={6}>
              <TextField
                select
                label={t("Gender")}
                value={formData.gender || ""}
                onChange={(e) => handleChange("gender", e.target.value)}
                error={!!errors["gender"]}
                helperText={errors["gender"]}
                fullWidth
                disabled={!options["gender"]}
              >
                {!options["gender"] ? (
                  <MenuItem value="">
                    <em>{t("Loading...")}</em>
                  </MenuItem>
                ) : (
                  options["gender"].map(
                    (option: { title: string; value: string | number }) => (
                      <MenuItem key={option.value} value={option.value}>
                        {option.title}
                      </MenuItem>
                    )
                  )
                )}
              </TextField>
            </Grid>
          </Grid>
        );
      case 1:
        return (
          <Grid container spacing={2} p={2}>
            <Grid size={12}>
              <Alert
                message={t(
                  "Succcessfuly created new member! Now choose a plan"
                )}
                showAlert={true}
                severity="success"
                autoClose
              />
            </Grid>
            <Grid size={6}>
              <TextField
                select
                label={t("Subcription Plan")}
                value={formData.subscriptionPlan}
                onChange={(e) =>
                  handleChangSubscription("subscriptionPlan", e.target.value)
                }
                fullWidth
              >
                {options["subscriptionPlan"].map(
                  (option: { title: string; value: string | number }) => (
                    <MenuItem key={option.value} value={option.value}>
                      {option.title}
                    </MenuItem>
                  )
                )}
              </TextField>
            </Grid>
            <Grid size={6}>
              <TextField
                select
                label={t("Employment")}
                value={formData.subscriptionPlan}
                onChange={(e) =>
                  handleChangSubscription("employment", e.target.value)
                }
                fullWidth
              >
                {options["employment"].map(
                  (option: { title: string; value: string | number }) => (
                    <MenuItem key={option.value} value={option.value}>
                      {option.title}
                    </MenuItem>
                  )
                )}
              </TextField>
            </Grid>
            {subscriptionData.subscriptionPlan === "VISIT_PASS" && (
              <Grid size={6}>
                <TextField
                  select
                  label={t("Visit Limit")}
                  value={formData.visitLimit}
                  type="number"
                  onChange={(e) =>
                    handleChangSubscription("visitLimit", e.target.value)
                  }
                  inputProps={{ min: 1 }}
                  fullWidth
                >
                  {[3, 6, 12, 24].map((count) => (
                    <MenuItem key={count} value={count}>
                      {count}
                    </MenuItem>
                  ))}
                </TextField>
              </Grid>
            )}
          </Grid>
        );
      case 2:
        return (
          <Box
            sx={{ maxWidth: 500, margin: "0 auto", textAlign: "center", p: 2 }}
          >
            <Typography variant="h5" gutterBottom>
              Total Price
            </Typography>
            <Typography variant="h3" color="primary" gutterBottom>
              $29.99
            </Typography>

            <Typography variant="subtitle1" gutterBottom>
              Choose your payment method:
            </Typography>

            <ToggleButtonGroup
              color="primary"
              value={paymentMethod}
              exclusive
              onChange={handlePaymentMethodChange}
              aria-label="Payment Method"
              sx={{ mt: 2 }}
            >
              <ToggleButton value="card" sx={{ width: 150, height: 80 }}>
                {t("Pay by Card")}
              </ToggleButton>
              <ToggleButton value="cash" sx={{ width: 150, height: 80 }}>
                {t("Pay by Cash")}
              </ToggleButton>
            </ToggleButtonGroup>
          </Box>
        );

      default:
        return "Unknown step";
    }
  };

  return (
    <>
      <Box sx={{ width: "100%" }}>
        <Stepper activeStep={activeStep} alternativeLabel>
          {steps.map((label) => (
            <Step key={label}>
              <StepLabel>{label}</StepLabel>
            </Step>
          ))}
        </Stepper>

        <Box sx={{ mt: 2, mb: 1 }}>{getStepContent(activeStep)}</Box>

        <Grid
          container
          spacing={2}
          sx={{
            display: "flex",
            justifyContent: "flex-end",
            mt: 2,
          }}
        >
          {activeStep !== 0 && (
            <Grid>
              <Button color="error" onClick={() => handleBack()}>
                {t("Back")}
              </Button>
            </Grid>
          )}

          <Grid>
            <Button onClick={() => handleNext()}>{t("Next")}</Button>
          </Grid>
        </Grid>
      </Box>
      <CustomModal
        open={openConfirm}
        onClose={() => setOpenConfirm(false)}
        title={t("Confirm Subscription")}
        width={"md"}
      >
        {/* Price Highlight */}
        <Paper
          elevation={3}
          sx={{
            p: 2,
            mb: 3,
            textAlign: "center",
            background: (theme) => theme.palette.success.light,
            color: (theme) => theme.palette.success.contrastText,
            borderRadius: 2,
          }}
        >
          <Typography variant="h5" fontWeight="bold">
            {t("Total Price")}: ${subscriptionData.price || "0.00"}
          </Typography>
        </Paper>

        {/* Confirmation Text */}
        <Typography variant="body1" sx={{ mb: 2 }}>
          {t("Are you sure you want to proceed with this subscription?")}
        </Typography>

        {/* Subscription Details */}
        <Paper variant="outlined" sx={{ p: 2, borderRadius: 2, mb: 3 }}>
          <Typography variant="subtitle1" sx={{ fontWeight: "bold" }}>
            {t("Plan")}:{" "}
            <Typography component="span" fontWeight="normal">
              {subscriptionData.subscriptionPlan}
            </Typography>
          </Typography>

          <Typography variant="subtitle1" sx={{ fontWeight: "bold" }}>
            {t("Employment")}:{" "}
            <Typography component="span" fontWeight="normal">
              {subscriptionData.employment}
            </Typography>
          </Typography>

          <Typography variant="subtitle1" sx={{ fontWeight: "bold" }}>
            {t("Payment Method")}:{" "}
            <Typography component="span" fontWeight="normal">
              {paymentMethod}
            </Typography>
          </Typography>
        </Paper>

        <Box display="flex" justifyContent="flex-end" gap={2}>
          <Button
            onClick={() => setOpenConfirm(false)}
            color="error"
            variant="outlined"
          >
            {t("Cancel")}
          </Button>
          <Button
            onClick={async () => {
              await callApi<any>({
                query: postSubscription(subscriptionData, id),
                auth: { setAuthedUser },
              });
              setOpenConfirm(false);
              setModalTitle(null);
              setRefreshTable && setRefreshTable((prev: boolean) => !prev);
            }}
            color="primary"
            variant="contained"
          >
            {t("Confirm")}
          </Button>
        </Box>
      </CustomModal>
    </>
  );
};

export default ClientsCreateForm;
